Implemented feature for request update
cyberdr0id/referral pull request #15
Opened 2021-12-30 13:33 UTC by cyberdr0id

2021-12-30 14:15 UTC, papahmsolo requested changes

2021-12-30 14:15 UTC, papahmsolo commented on internal/handler/handlers.go
>  	}
Can new status be any string or only a valid status?

2021-12-30 14:15 UTC, papahmsolo commented on internal/handler/handlers.go
>  		return
Why not using sendResponse?

2021-12-30 20:43 UTC, cyberdr0id commented on internal/handler/handlers.go
>  	}
I skipped the status check before approval

2021-12-31 11:09 UTC, papahmsolo approved these changes

2021-12-31 11:09 UTC, merged