Implemented pagination
cyberdr0id/referral pull request #19
Opened 2022-01-10 13:07 UTC by cyberdr0id

2022-01-10 13:32 UTC, papahmsolo approved these changes
👀

2022-01-10 13:32 UTC, papahmsolo commented on internal/handler/handlers.go
>  	}
Single validate function

2022-01-10 13:32 UTC, papahmsolo commented on internal/handler/handlers.go
>  	return ok, nil
returns error only

2022-01-12 21:40 UTC, papahmsolo requested changes
👀

2022-01-12 21:40 UTC, papahmsolo commented on internal/service/referral.go
> +	}
Already explained in the previous comment

2022-01-12 21:40 UTC, papahmsolo commented on internal/repository/referral.go
> +				`, id, pageSize, offset)
We're not validating and escaping input. Potential SQL injection ([more info](https://go.dev/doc/database/sql-injection)). Have you run a linter here?

2022-01-12 21:40 UTC, papahmsolo commented on internal/repository/referral.go
> +				`, id, status, pageSize, offset)
This is almost identical to previous query, if you can find a way to minimize code duplication that'd be great. If not, that's fine, leave it as is.

2022-01-13 10:58 UTC, cyberdr0id commented on internal/repository/referral.go
> +				`, id, pageSize, offset)
yep, but nothing happened

2022-01-13 15:03 UTC, papahmsolo requested changes
👀

2022-01-13 15:03 UTC, papahmsolo commented on internal/repository/referral.go
> +	rows, err := r.db.Query(query, whereVal...)
queries with and without status are very similar

2022-01-13 15:03 UTC, papahmsolo commented on internal/handler/handlers.go
> +	}
single validation func

2022-01-14 17:54 UTC, papahmsolo approved these changes

2022-01-14 17:54 UTC, merged