Started integration testing implementing
cyberdr0id/referral pull request #26
Opened 2022-01-27 10:48 UTC by cyberdr0id

2022-02-03 08:11 UTC, gordonBusyman requested changes
Description of the PR is missing

2022-02-03 08:11 UTC, gordonBusyman commented on tests/main_test.go
> +	s.clearTables()
Why it does the same with `TearDownTest()`?

2022-02-03 08:52 UTC, cyberdr0id commented on tests/main_test.go
> +	s.clearTables()
To always work with an empty database before testing and exclude the situation of storing data in the database after

2022-02-03 08:56 UTC, gordonBusyman approved these changes

2022-02-04 09:37 UTC, gordonBusyman approved these changes
One comment, not blocking

2022-02-04 09:37 UTC, gordonBusyman commented on tests/database_test.go
> +	s.NoError(err)
You can probably move this to a separate function as it called several times here

2022-02-04 09:57 UTC, cyberdr0id commented on tests/database_test.go
> +	s.NoError(err)
I thought about it, but I decide to make like this, cause I thought that it's bad practice in tests to move code that called several times to a separate function and I thought that it's minor inaccuracy

2022-02-04 09:58 UTC, gordonBusyman commented on tests/database_test.go
> +	s.NoError(err)
That's ok, not critical 👍

2022-02-07 15:24 UTC, merged