Created handlers, requests structures and validated requests data
cyberdr0id/referral pull request #4
Opened 2021-10-25 17:32 UTC by cyberdr0id

2021-11-01 14:28 UTC, papahmsolo requested changes
👀

2021-11-01 14:28 UTC, papahmsolo commented on pkg/hash/hash.go
> +}
No need to declare err here

2021-11-01 14:28 UTC, papahmsolo commented on internal/repository/database.go
> +	}
- Can we wrap these errors giving some more context?
- Is there any particular reason we want to declare errors as `errSQLConnection`? Also note it's unexported

2021-11-01 14:28 UTC, papahmsolo commented on internal/handler/handlers.go
> +func (r *AuthRequest) CheckDataCorrectness() error {
We're actually _validating_ the request, can we give it more descriptive name?

2021-11-01 14:28 UTC, papahmsolo commented on docs/swagger.yml
401 is not a bad request, it's unauthenticated

2021-11-01 14:28 UTC, papahmsolo commented on internal/handler/handlers.go
> +	}
Is it a server or user error?

2021-11-01 15:44 UTC, cyberdr0id commented on internal/repository/database.go
> +	}
I decided to remove custom errors, because they have the same content as errors returned by methods

2021-11-08 15:07 UTC, papahmsolo requested changes
Looks good

2021-11-22 15:41 UTC, papahmsolo approved these changes

2021-11-22 15:41 UTC, papahmsolo commented on internal/handler/handlers.go
> +	errWrongPassword = errors.New("wrong password for inputed user")
- common error "invalid param"

2021-11-22 15:41 UTC, papahmsolo commented on internal/handler/handlers.go
> +}
- response?

2021-11-22 15:41 UTC, papahmsolo commented on internal/handler/handlers.go
> +	pass, _ := hash.HashPassword(request.Password)
- handle error

2021-11-22 15:41 UTC, papahmsolo commented on internal/handler/handlers.go
> +	id, err := s.Repo.CreateUser(request.Name, pass)
service.CreateUser()

2021-11-22 15:41 UTC, papahmsolo commented on internal/handler/handlers.go
> +	if errors.Is(err, repository.ErrNoUser) {
service error user already exists

2021-11-22 15:41 UTC, papahmsolo commented on internal/handler/handlers.go
> +	if errors.Is(err, repository.ErrNoUser) {
handler interacts with service layer

2021-11-22 15:41 UTC, papahmsolo commented on internal/handler/handlers.go
> +	if !ok {
validation function

2021-11-22 15:41 UTC, merged